#+TITLE: y-arena
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Repository Information
  - Name :: y-arena
  - Version :: 1.0.0
  - License :: BSD
  - URL :: https://github.com/janelia-experimental-technology/y-arena
  - Author :: Peter Polidoro
  - Email :: peterpolidoro@gmail.com

** Description

   Main repository for the Turner Lab Y-Arena.

* Usage

** Matlab

   #+BEGIN_SRC matlab
     yArenaNode = ros2node('y_arena_matlab_node')
     arenaValvesOpenPub = ros2publisher(yArenaNode,'/arena_valves_open','y_arena_interfaces/ArenaValves')
     arenaValvesOpenMsg = ros2message('y_arena_interfaces/ArenaValves')
     arenaValvesOpenMsg.arena = 0
     arenaValvesOpenMsg.valves = {0,2,1}
     send(arenaValvesOpenPub,arenaValvesOpenMsg)
   #+END_SRC

* System Architecture

** Arena

   Each arena contains three arms. The three arms are arranged so the arena
   looks like the letter "Y". A fly is placed in the arena and can walk up and
   down each of the three arms. Each arm has three valves, allowing the user to
   select one of three odors for each arm at a time. So there are a total of
   nine valves for each arena. Three and only three valves are open at any given
   time, one for each arena arm.

*** Vector Representation of Open Valves

    |             | ARM 0  | ARM 1  | ARM 2  |
    |-------------+--------+--------+--------|
    | VALVE 2     | OPEN   | CLOSED | CLOSED |
    | VALVE 1     | CLOSED | OPEN   | CLOSED |
    | VALVE 0     | CLOSED | CLOSED | OPEN   |
    | valves_open | 2      | 1      | 0      |

    |             | ARM 0  | ARM 1  | ARM 2  |
    |-------------+--------+--------+--------|
    | VALVE 2     | OPEN   | OPEN   | OPEN   |
    | VALVE 1     | CLOSED | CLOSED | CLOSED |
    | VALVE 0     | CLOSED | CLOSED | CLOSED |
    | valves_open | 2      | 2      | 2      |

    The three open valves can be represented by a vector, where each element of
    the vector represents one of the arms, ARM 0, ARM 1, and ARM 2. Each vector
    element can take one of three values, 0, 1, or 2, representing VALVE 0,
    VALVE 1, or VALVE 2.

* Setup

  [[./setup/README.org]]

* Firmware

  [[./firmware/README.org]]

* Hardware

  [[./hardware/README.org]]

* Software

  [[./software/README.org]]
