#+TITLE: y-arena
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Repository Information
  - Name :: y-arena
  - Version :: 1.0.0
  - License :: BSD
  - URL :: https://github.com/janelia-experimental-technology/y-arena
  - Author :: Peter Polidoro
  - Email :: peterpolidoro@gmail.com

** Description

   Main repository for the Turner Lab Y-Arena.

* Usage

** Matlab

   #+BEGIN_SRC matlab
     yArenaNode = ros2node('y_arena_matlab_node')
     arenaOdorsPub = ros2publisher(yArenaNode,'/arena_odors','y_arena_interfaces/ArenaOdors')
     arenaOdorsMsg = ros2message('y_arena_interfaces/ArenaOdors')
     arenaOdorsMsg.arena = uint8(0)
     arenaOdorsMsg.odors = uint8([0 2 1])
     send(arenaOdorsPub,arenaOdorsMsg)
   #+END_SRC

** Linux Command Line Using Docker

   #+BEGIN_SRC sh
     docker build -t y_arena_odor_controller:latest ./software/y_arena_odor_controller_ros/
     docker run --rm --net=host --pid=host -it y_arena_odor_controller:latest
     ros2 service call /get_arenas_available y_arena_interfaces/srv/GetArenas
     ros2 topic pub --once /arena_odors y_arena_interfaces/msg/ArenaOdors "{arena: 0, odors: [0, 2, 1]}"
   #+END_SRC

* System Architecture

** Arena

   Each arena contains three arms. The three arms are arranged so the arena
   looks like the letter "Y". A fly is placed in the arena and can walk up and
   down each of the three arms. Each arm has three odors, allowing the user to
   select one of three odors for each arm at a time. So there are a total of
   nine odors for each arena. Three and only three odors are active at any given
   time, one active odor for each arena arm.

*** Vector Representation of Arena Odors

    arena_odors = [arm 0 odor, arm 1 odor, arm 2 odor]

    The three active odors can be represented by a vector, where each element of
    the vector represents one of the arms, ARM 0, ARM 1, and ARM 2. Each vector
    element can take one of three values, 0, 1, or 2, representing ODOR 0, ODOR
    1, or ODOR 2.

**** arena_odors [0, 2, 1]

     |       | ODOR 0   | ODOR 1   | ODOR 2   |
     |-------+----------+----------+----------|
     | ARM 2 | INACTIVE | ACTIVE   | INACTIVE |
     | ARM 1 | INACTIVE | INACTIVE | ACTIVE   |
     | ARM 0 | ACTIVE   | INACTIVE | INACTIVE |

**** arena_odors [0, 0, 0]

     |       | ODOR 0   | ODOR 1   | ODOR 2   |
     |-------+----------+----------+----------|
     | ARM 2 | ACTIVE   | INACTIVE | INACTIVE |
     | ARM 1 | ACTIVE   | INACTIVE | INACTIVE |
     | ARM 0 | ACTIVE   | INACTIVE | INACTIVE |


* Connect to ycontroller from Host Machine

** Cockpit Web Console

   https://ycontroller:9090

   Local Network

   https://ycontroller.local:9090

   Inside Janelia

   https://ycontroller.hhmi.org:9090


** SSH

   #+BEGIN_SRC sh
     ssh yuser@ycontroller
     # local network
     ssh yuser@ycontroller.local
     # inside Janelia
     ssh yuser@ycontroller.hhmi.org
   #+END_SRC

* Setup

  [[./setup/README.org]]

* Firmware

  [[./firmware/README.org]]

* Hardware

  [[./hardware/README.org]]

* Software

  [[./software/README.org]]
